listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

# VHOST 1: Público (Ingestão e Transcodificação)
vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://pet-api:3000/api/video/auth-publish;
        on_unpublish    http://pet-api:3000/api/video/on-unpublish;
    }

    # Transcodificador simplificado para estabilidade máxima
    transcode {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg; 
        engine clean {
            enabled         on;
            vcodec          libx264;
            vbitrate        1000;
            vfps            20;
            vwidth          1280;
            vheight         720;
            vthreads        2;
            vprofile        baseline; # Perfil mais leve
            vpreset         ultrafast;
            vparams {
                tune        zerolatency;
            }
            acodec          none; # Desativa áudio temporariamente para estabilizar o sinal
            output          rtmp://127.0.0.1:1935/live/[stream]?vhost=hls.internal;
        }
    }

    # Mapeia o acesso público para a pasta do vhost interno
    http_static {
        enabled     on;
        mount       /live;
        dir         ./objs/nginx/html/hls.internal/live;
    }
}

# VHOST 2: Entrega HLS (Interno)
vhost hls.internal {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    5;      # Segmentos maiores = mais estabilidade
        hls_window      30;     # Mantém 30 segundos de vídeo no "passado"
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_cleanup     on;
        hls_dispose     30;     # Não deleta arquivos imediatamente após queda
    }
}
