listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://pet-api:3000/api/video/auth-publish;
        on_unpublish    http://pet-api:3000/api/video/on-unpublish;
    }

    hls {
        enabled         on;
        hls_fragment    4;
        hls_window      20;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_cleanup     on;
        hls_dispose     30;
    }

    # Transcodificador focado em COMPATIBILIDADE ESTRITA com navegadores web (hls.js)
    transcode ingest {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg; 
        engine clean {
            enabled         on;
            vcodec          libx264;
            vbitrate        800;
            vfps            20;
            vwidth          1280;
            vheight         720;
            vthreads        1;
            # O perfil 'baseline' e formato de pixel 'yuv420p' previnem o 'bufferAppendError' no Chrome
            vprofile        baseline;
            vpreset         ultrafast;
            vparams {
                tune        zerolatency;
                pix_fmt     yuv420p;
            }
            # Áudio completamente desativado para garantir que não seja a causa do erro de sincronia
            acodec          none;
            output          rtmp://127.0.0.1:1935/live/[stream];
        }
    }
}
