listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost __defaultVhost__ {
    play {
        mix_correct     on;
    }

    # Transcodificador: Pega do 'live' (DVR) e joga pro 'clean'
    transcode {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine clean {
            enabled         on;
            vcodec          libx264;
            vbitrate        1000;
            vfps            20;
            vwidth          1280;
            vheight         720;
            vthreads        2;
            vprofile        baseline;
            vpreset         ultrafast;
            vparams {
                tune        zerolatency;
                g           40;
            }
            # Comando correto para mudo no SRS 5
            acodec          none; 
            output          rtmp://127.0.0.1:1935/clean/[stream];
        }
    }
}

# Vhost para gerar o HLS do sinal limpo
vhost 127.0.0.1 {
    hls {
        enabled         on;
        hls_fragment    4;
        hls_window      40;
        hls_path        ./objs/nginx/html;
        # Força a criação da pasta 'clean'
        hls_m3u8_file   clean/[stream].m3u8;
        hls_ts_file     clean/[stream]-[seq].ts;
        hls_cleanup     on;
    }
}
